### ISSUE TITLE
Mobile Header Doesn't Match Header Style Settings

### ISSUE THREAD

**Issue by gregforcey** [TryGhost/Headline#10]
If `Header Style` is set for `Accent Color` or `Dark`, this setting is not reflected when viewing the site in mobile or tablet mode. 

In this case, when clicking the pancake icon, only a white header is shown. This means that the primary links and search icon are not visible because they are also white. Thanks for the fix.

**Comment by minimaluminium** [comment]
Hey @gregforcey, thanks for the report! This issue is now fixed in https://github.com/TryGhost/Themes/commit/1649cf20afdf9763f91a6d140887bbc6e0548f86. Should be fixed when you re-install the theme.
