### ISSUE TITLE
On index pages, multiple author names display without spaces

### ISSUE THREAD

**Issue by royalfig** [TryGhost/Headline#11]
In `loop-grid.hbs`, multiple authors run together

https://github.com/TryGhost/Headline/blob/4425d4a66d8e0c53b0ee017c08b78c1bc372974d/partials/loop-grid.hbs#L34

This will include a comma-separated list:

```handlebars
{{#foreach authors}}{{#if @first}}{{name}}{{else}}, {{name}}{{/if}}{{/foreach}}
```

If this looks good, I can make a PR 😄

**Comment by minimaluminium** [comment]
That looks perfect, thanks @royalfig 🙂

**Comment by royalfig** [comment]
updated on Themes repo
