### ISSUE TITLE
Comments vissible on both pages and posts

### ISSUE THREAD

**Issue by alternaivan** [TryGhost/Headline#4]
Hello,

I've been using this theme for my blog, and I've enabled cove comments on the site. I have followed instructions on how to set them up, and everything is working fine, however, I can see those comments both on pages and posts.

Since I'm not well versed in the templating language being used for themes, is there some flag, or tag that I can add to `post.hbs` file that will display those comments only on posts, and not on pages?

Thanks,
Marjan

**Comment by orencohendev** [comment]
This theme doesn't have a template for pages but you can fix that quite easily.

1. duplicate the post.hbs file and call it page.hbs
2. remove from page.hbs the comment section you initially added.
3. zip the theme folder and upload it to ghost.
4. activate the theme.

That should do it.

**Comment by orencohendev** [comment]
While you're at it, you may want to add your comments to the full and wide templates since you may want to use them in the future for some posts, and they won't have comments either.

**Comment by alternaivan** [comment]
Hi @orencohendev,

Thanks for the instructions. I've added everything as you described and it and it works! 😄 

Thanks again,
Marjan
