### ISSUE TITLE
Publication cover not working

### ISSUE THREAD

**Issue by jacotec** [TryGhost/Headline#5]
I've created a nice background for my site header and uploaded it as publication cover - but it's simply not working.

<img width="343" alt="2022-04-25_21-53-41" src="https://user-images.githubusercontent.com/3321655/165164436-4d1e126c-fa74-44b7-a4be-96f76e76f7be.png">

I'd expect this to be the background in this area, like in Casper:

<img width="1427" alt="2022-04-25_21-54-55" src="https://user-images.githubusercontent.com/3321655/165164685-4b50a180-3ada-424c-897a-df4f2a725df7.png">

But whatever I try, the publication cover is simply ignored.

**Comment by minimaluminium** [comment]
Hey @jacotec, publication cover is an optional setting as a large background image is great for some themes. Headline's homepage was designed to be clean sections of news feed and doesn't use cover image on its homepage.
